version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./BackEnd:/app/BackEnd

  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
